sudo: required
services:
  - docker

before_install:
  - docker build -t agsaacitdpps/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true agsaacitdpps/docker-react npm run test

deploy:
